version: '3'
services:
  app:
    restart: always
    image: opensourcepolitics/osp-app:latest
    volumes:
    - .:/app
    - bundle:/usr/local/bundle
    - node_modules:/app/node_modules
    environment:
    - PORT=3000
    - DATABASE_HOST=pg
    - DATABASE_USERNAME=postgres
    - RAILS_ENV=production
    - SECRET_KEY_BASE=f97271c0788641d98a8a7feaa2b8b40fdc28f83285a4f23703abdaf3ac0641a4f047788fd15e4b698e026325ebda371573c370fd6a3bdb720d7e04a580b84882
    ports:
    - 3000:3000
    links:
    - pg
    command: bundle exec puma
  pg:
    restart: always
    image: postgres
    volumes:
    - pg-data:/var/lib/postgresql/data
volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
