:concurrency: 5
:queues:
- default
- metrics
- mailers
- newsletter
- events
- scheduled

:schedule:
  CalculateAllMetrics:
    every: ['24h', first_in: '1m']
    class: CalculateAllMetricsJob
    queue: scheduled
  PreloadOpenData:
    every: ['24h', first_in: '1m']
    class: PreloadOpenDataJob
    queue: scheduled
  OrdersReminder:
    every: ['24h', first_in: '1m']
    class: OrdersReminderJob
    queue: scheduled
