name: "[CI] ILOA"
on:
  push:
    branches:
      - develop
      - master
      - release/*
      - "*-stable"
  pull_request:
    branches:
      - "*"

env:
  CI: "true"
  SIMPLECOV: "true"
  RUBY_VERSION: 2.5.3
  NODE_VERSION: 12.9.1
  BUNDLER_VERSION: 2.0.2

jobs:
  main:
    name: Install and Lint OSP App tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        if: "github.ref != 'refs/heads/master' || github.ref != 'refs/heads/develop'"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Recover Ruby dependency cache
        uses: actions/cache@v1
        with:
          path: ./vendor/bundle
          key: ${{ runner.OS }}-rubydeps-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-rubydeps-${{ env.cache-name }}-
            ${{ runner.OS }}-rubydeps-
            ${{ runner.OS }}-
      - run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler -v ${{ env.BUNDLER_VERSION }}
          bundle install --path vendor/bundle --jobs 4 --retry 3
        name: Install Ruby deps
      - run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load
          bundle exec rake db:seed
        name: Create test app
      - run: npm ci
        name: Install JS deps
      - run: bundle exec rubocop -P
        name: Lint Ruby files
      - run: ./.github/run_erblint.sh
        name: Lint ERB files
      - run: bundle exec rake assets:precompile
        name: Assets precompilation
